# Generated by Django 5.2.8 on 2025-11-21 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_manager_api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
