# Generated by Django 5.2.8 on 2025-12-24 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_manager_api', '0009_delivery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='delivery_id',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='product_id',
        ),
        migrations.AddField(
            model_name='delivery',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='delivery',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='product_manager_api.order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='product_manager_api.product'),
            preserve_default=False,
        ),
    ]
