# Generated by Django 5.2.8 on 2026-01-13 08:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product_manager_api", "0010_remove_delivery_customer_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="delivery",
            options={"verbose_name_plural": "Delivery"},
        ),
        migrations.AddField(
            model_name="product",
            name="discount_end_date",
            field=models.DateField(
                blank=True, help_text="End date for discount", null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="discount_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Discount percentage (0-100)",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="discount_start_date",
            field=models.DateField(
                blank=True, help_text="Start date for discount", null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="original_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Original price before discount",
                max_digits=10,
                null=True,
            ),
        ),
    ]
