# Generated by Django 5.2.8 on 2026-01-13 09:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "product_manager_api",
            "0011_alter_delivery_options_product_discount_end_date_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="RefundRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_id", models.IntegerField()),
                ("product_name", models.CharField(max_length=200)),
                (
                    "quantity",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "purchase_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "refund_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("customer_id", models.CharField(db_index=True, max_length=50)),
                ("customer_name", models.CharField(max_length=200)),
                ("customer_email", models.EmailField(max_length=254)),
                (
                    "reason",
                    models.TextField(help_text="Customer's reason for refund request"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("completed", "Completed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "evaluated_by",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("evaluation_notes", models.TextField(blank=True, null=True)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("evaluated_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refund_requests",
                        to="product_manager_api.order",
                    ),
                ),
                (
                    "order_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refund_requests",
                        to="product_manager_api.orderitem",
                    ),
                ),
            ],
            options={
                "ordering": ["-requested_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "requested_at"],
                        name="product_man_status_6386ab_idx",
                    ),
                    models.Index(
                        fields=["customer_id", "status"],
                        name="product_man_custome_14bcd8_idx",
                    ),
                    models.Index(
                        fields=["order", "status"],
                        name="product_man_order_i_62676d_idx",
                    ),
                ],
            },
        ),
    ]
