# Generated by Django 5.2.8 on 2026-01-13 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product_manager_api", "0012_refundrequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("processing", "Processing"),
                    ("in-transit", "In Transit"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="processing",
                max_length=20,
            ),
        ),
    ]
