# Generated by Django 4.2.7 on 2025-11-12 18:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("model", models.CharField(max_length=100)),
                ("serial_number", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField()),
                (
                    "quantity_in_stock",
                    models.IntegerField(
                        default=0,
                        help_text="Number of items available in stock",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Sale price of the product",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("warranty_status", models.CharField(blank=True, max_length=200)),
                ("distributor", models.CharField(blank=True, max_length=200)),
                ("category", models.CharField(max_length=100)),
                (
                    "cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Product cost for profit/loss calculation (defaults to 50% of sale price)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "delivery_id",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("customer_id", models.CharField(db_index=True, max_length=50)),
                ("customer_name", models.CharField(max_length=200)),
                ("customer_email", models.EmailField(max_length=254)),
                (
                    "product_id",
                    models.IntegerField(help_text="Reference to Product ID"),
                ),
                ("product_name", models.CharField(max_length=200)),
                (
                    "quantity",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("delivery_address", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("processing", "Processing"),
                            ("in-transit", "In Transit"),
                            ("delivered", "Delivered"),
                        ],
                        db_index=True,
                        default="processing",
                        max_length=20,
                    ),
                ),
                ("order_date", models.DateField()),
                ("delivery_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
                "ordering": ["-order_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "order_date"],
                        name="product_man_status_147782_idx",
                    ),
                    models.Index(
                        fields=["customer_id", "order_date"],
                        name="product_man_custome_29595b_idx",
                    ),
                ],
            },
        ),
    ]
